name: jcnws
favicon: null
layout_spectrum: 0.25369
typography_spectrum: 0.32499
title: juice news beta
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#df7305'
    - '#f18617'
    - '#ffffff'
    - '#f8dfc6'
    - '#eca65d'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
